PRICE_INDEX = 0
VOLUME_INDEX = 1
TIME_INDEX = 2
SIDE_INDEX = 3
MARKET_INDEX = -1
TRADE_LIST = 1

REST_TIMESTAMP_INDEX = 0
REST_OPEN_INDEX = 1
REST_HIGH_INDEX = 2
REST_LOW_INDEX = 3
REST_CLOSE_INDEX = 4
REST_VOLUME_INDEX = 6

REST_PRICE_INDEX = 0
REST_TRADE_VOLUME_INDEX = 1
REST_TRADE_TS_INDEX = 2
REST_DIRECTION_INDEX = 3
